# try exception
try:
	# var angka1 = 9
	angka1 = 9
	# cetak var angka1(9) + buah
	print(angka1 + "buah")
	
# ditangkap bila ada error
except:
	print("terdapat error ... hmmm")